Python download script for macos users
meta-llama/llama pull request #422
Opened 2023-07-19 17:20 UTC by adnanboz

I had issues with installing wget on my mac and decided to write a python version. For those who have similar issues.

2023-07-20 01:19 UTC, ParsaHonarmand approved these changes

2023-07-20 01:30 UTC, ParsaHonarmand requested changes
Getting the following error that may need try/catching. Any ideas why I'm getting back a 403? Just got my link from Meta AI

![Screenshot 2023-07-19 at 7 29 15 PM](https://github.com/facebookresearch/llama/assets/40723547/03fbe9d0-9f71-4378-8c37-a9b29e3e1747)

2023-07-21 01:59 UTC, adnanboz commented
Unfortunately that is the problem everyone is having https://github.com/facebookresearch/llama/issues/317#issuecomment-1644201717 . I was able to download the usage policy but it is also not working for me anymore. I requested another key as well as suggested in the thread.

2024-09-11 07:43 UTC, artiebits commented
@adnanboz @ParsaHonarmand have you checked this FAQ https://github.com/facebookresearch/llama/blob/bug-fix-Sep6/Download.md?

Closing this PR for now as it has been inactive for a year and the original issue was closed #317. Feel free to reopen if issue persists.

2024-09-11 07:43 UTC, closed without merging